//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador_WorkSpace
    {
        public int IdAdministrador_WorkSpace { get; set; }
        public Nullable<int> IdAdministrador { get; set; }
        public Nullable<int> IdWorkSpace { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual WorkSpace WorkSpace { get; set; }
    }
}
