//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CmsEncuestasEntities : DbContext
    {
        public CmsEncuestasEntities()
            : base("name=CmsEncuestasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Administrador_WorkSpace> Administrador_WorkSpace { get; set; }
        public virtual DbSet<BaseDeDatos> BaseDeDatos { get; set; }
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<EstatusEncuesta> EstatusEncuesta { get; set; }
        public virtual DbSet<Preguntas> Preguntas { get; set; }
        public virtual DbSet<Respuestas> Respuestas { get; set; }
        public virtual DbSet<TipoControl> TipoControl { get; set; }
        public virtual DbSet<TipoEncuesta> TipoEncuesta { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_EstatusEncuesta> Usuario_EstatusEncuesta { get; set; }
        public virtual DbSet<UsuarioRespuestas> UsuarioRespuestas { get; set; }
        public virtual DbSet<WorkSpace> WorkSpace { get; set; }
    }
}
